name: my-azureml-env
dependencies:
  - python=3.8
  - scikit-learn
  - joblib
  - pip:
    - azureml-sdk
    - azureml-inference-server-http
  - apt:  # This section allows you to include system packages
    - libtinfo6  # Ensure the correct version of libtinfo is installed
